### ISSUE TITLE
Module.Java - one to many annotations

### ISSUE THREAD

**Issue by mccollum3d** [revaturelabs/cms-backend#10]
This class has not yet been annotated to support the one to many relationship in hibernate, which should look something like this.
```java
@OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinTable(name="module_tag_jt", inverseJoinColumns=@JoinColumn(name="moduleId"), joinColumns=@JoinColumn(name="tagId"))
	private Module modules;
```

**Comment by alex-briggs** [comment]
Added/fixed the one to many mapping but still working on making sure the mapping is actually happening in the database 

will open a new issue for the mapping to the database problem

@OneToMany(targetEntity = Tag.class, fetch = FetchType.LAZY) looks like this at the moment 05/25
