### ISSUE TITLE
Issue connecting to Postgre Database

### ISSUE THREAD

**Issue by MattCowin** [revaturelabs/cms-backend#12]
Issues connecting to Postgre database. Getting java.lang.reflect.InvocationTargetException: null when switching from H2 database to Postgre. @Quinn-Donnelly not sure if it is something added in the application.properties that should not be there.

**Comment by Quinn-Donnelly** [comment]
So long as the connection information sent works in DBeaver or SQL workbench then it means the database is fine. Make sure you set the sql dialect to Postgre. @MattCowin
