### ISSUE TITLE
Casing of tags when searching

### ISSUE THREAD

**Issue by Tech314** [revaturelabs/cms-backend#25]
Currently when searching for content via tags the casing that we search by is important. We should add in the ability to ignore case when searching so that we don't need to search for the tag exactly as it was typed when creating it.

**Comment by miyazaki1** [comment]
Matt brought up when searching for queries, there is a "like" and we also have the option toUpper, toLower respectively.

**Comment by alex-briggs** [comment]
Yes Matt already fixed it
