### ISSUE TITLE
TagRepository: Need new JPA Query

### ISSUE THREAD

**Issue by mccollum3d** [revaturelabs/cms-backend#6]
The content creation team needs a new endpoint in the TagController, and query in the Repo (plus method in the service layer.)

This endpoint should by "FindByName" (or appropriate column name) to return a list of all Tags from the table. Discuss with Dan/Terry. This data is needed to populate a form of all possible tags to attach to a piece of content.

**Comment by nateman9001** [comment]
should be functional now.

**Comment by MattCowin** [comment]
Successfully tested
