### ISSUE TITLE
Tag.Java: Code Review

### ISSUE THREAD

**Issue by mccollum3d** [revaturelabs/cms-backend#9]
- The code has been pushed with merge conflicts in it, please fix so it will compile.
```java
private String type;
<<<<<<< HEAD
	
	@Column(name = "CONTENT_ID")
	private long contentId;
	
=======
```

- Missing hashCode() and equals()

- Standardization: Class should have following structure:
1. variables
2. constructors
3. getters/setters
4. hashcode / equals
5. toString

**Comment by nateman9001** [comment]
I loaded it up and there seems to be a hashcode() and an equals().

**Comment by mccollum3d** [comment]
Please push your changes to the base branch, base branch is still missing hashcode() and equals(). Please move those methods and toString() to the end of the class, so they are below the getters and setters (if they are not already.) Thanks. @nateman9001

**Comment by nateman9001** [comment]
Oh wait, this was for the model Tag, not Content! Misunderstood. Yes, it should be fixed now.
